baseURL = 'https://tutors-in-action.org/'
languageCode = 'en-my'
title = 'Tutors In Action Malaysia (TIA)'
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true

[params]
subtitle = 'Persatuan Pelajar Bantu Pelajar Malaysia (PPBPM)'
description = 'We are a team of Malaysian youths hoping to help SPM students achieve their best.'
inspiration = 'Exacerbated by class disruptions during the pandemic, we realised that not everyone had the privilege of receiving one-to-one guidance from teachers on topics they may struggle with.'
aim = 'We aim to assist struggling Malaysian youth who lack academic support primarily through specialised online one-to-one or group tutoring by our own team of bright and accomplished volunteer tutors. Furthermore, we plan to use our platform to expand our reach by means of collaborations, fundraisers and more.'
tutorSignUpLink = 'https://docs.google.com/forms/d/e/1FAIpQLSeHHVjR6okfiQl1VurDHEDGUQGbNG6GHUkv2iOeWxWrrm-TmQ/viewform?usp=sharing'
tuteeSignUpLink = 'https://docs.google.com/forms/d/e/1FAIpQLScR3awG1owNh50QbpJxPZPEkCUyCT5UOnhE1jEp6Soe6456cQ/viewform?usp=sharing'
resourcesGoogleDriveFolderLink = 'https://drive.google.com/drive/folders/1rjg6h0bArc4QbKTAdAV6O8mYe5dVYlil?usp=drive_link'
pages = [
    ['About', 'about'],
    ['Projects', 'projects'],
    ['Resources', 'resources'],
    ['Guideline', 'guideline']
]
impacts = [
    [1462, "tutors recruited"],
    [2254, "tutees impacted"],
    [4228, "hours of tutoring"]
]
socials = [
    ["svg/facebook.svg", "https://www.facebook.com/tutors.in.action.malaysia"],
    ["svg/instagram.svg", "https://www.instagram.com/tutors.in.action/"],
    ["svg/telegram.svg", "https://t.me/TIA_helpbot"],
    ["svg/youtube.svg", "https://www.youtube.com/@tutorsinactionmalaysia"],
    ["svg/discord.svg", "https://discord.com/invite/7AE6cGVg2Y"],
    ["svg/linkedin.svg", "https://www.linkedin.com/company/tutors-in-action-malaysia/"],
    ["svg/xiaohongshu.svg", "https://www.xiaohongshu.com/user/profile/62f653c1000000001f005342"]
]
joinUsImages = [
    "guideline/joinus.jpg",
    "guideline/joinus-2.jpg",
    "guideline/joinus-3.jpg",
    "guideline/joinus-4.jpg"
]

[module]
[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "node_modules/countup.js/dist"
target = "static/countup"

[[module.mounts]]
source = "node_modules/bootstrap/dist"
target = "static/bootstrap"

[[module.mounts]]
source = "node_modules/jquery/dist"
target = "static/jquery"

[[module.mounts]]
source = "node_modules/jquery.easing"
target = "static/jquery.easing"

[[module.mounts]]
source = "node_modules/masonry-layout/dist"
target = "static/masonry-layout"